<div id="wrapper">
  <p>Pour accéder à cette partie du site, vous avez besoin de votre eID</p>
  <p>Si vous avez des difficultés à utiliser votre eID pour vous authentifier, voici quelques informations:</p>

<br>
Vous avez besoin :
<ul><li><strong>de votre carte eID <u>ET</u> de son CODE PIN.</strong></li>
<li><strong>d'un lecteur de carte eID.</strong></li>
<li>d'installer le <strong>programme pour lire la carte eID</strong>, à télécharger sur : <a href="http://eid.belgium.be"> http://eid.belgium.be. </a>(Icône eID Quick Install). <br>De plus amples informations sur la carte eID et le lecteur de carte sont également reprises sur le site.</li>
</ul>
Vous pouvez alors vérifier le bon fonctionnement de votre installation sur <a href="http://www.test.eid.belgium.be/">http://www.test.eid.belgium.be/</a>.<br><br><br>

<strong>FAQ</strong> :
<br>
<SPAN style="color:#FF0000">Le programme est installé mais je n'arrive pas à lire l'eID:</SPAN>
<br>Des mises à jour de configuration de navigateur (par ex. Internet Explorer, Firefox) sont disponibles sur le site de Fedict pour pouvoir utiliser l'eID : <a href="http://eid.belgium.be/fr/utiliser_votre_eid/besoin_d_aide/problemes_avec_l_installation/"> http://eid.belgium.be/fr/utiliser_votre_eid/besoin_d_aide/problemes_avec_l_installation/ </a> 
<br>
<br>
<SPAN style="color:#FF0000">Problème de connexion possible lors d'authentifications successives avec 2 eID:</SPAN>
<br>Avec certains navigateurs (comme Internet Explorer), la personne authentifiée en premier doit <u>fermer le navigateur</u> pour que l'autre personne puisse se connecter avec sa propre eID.

</div>
